// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCORCxZ4Ryj9bsay5tQHz0rXrThcgTTy9Y',
    appId: '1:550492156639:web:8451728831157a82faaf6a',
    messagingSenderId: '550492156639',
    projectId: 'my-first-project-fd056',
    authDomain: 'my-first-project-fd056.firebaseapp.com',
    storageBucket: 'my-first-project-fd056.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAY9XikZ01a7q7Gh0-Rla3IS0aBK7ll90',
    appId: '1:550492156639:android:fec32f678e8d41ecfaaf6a',
    messagingSenderId: '550492156639',
    projectId: 'my-first-project-fd056',
    storageBucket: 'my-first-project-fd056.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF_Go7fJHCRMAGscxrAjBr7VUsmE3j7kQ',
    appId: '1:550492156639:ios:c17bcba3bc3191abfaaf6a',
    messagingSenderId: '550492156639',
    projectId: 'my-first-project-fd056',
    storageBucket: 'my-first-project-fd056.appspot.com',
    iosClientId: '550492156639-hhl26d696pmdiqbg0916ftik13a76fa7.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF_Go7fJHCRMAGscxrAjBr7VUsmE3j7kQ',
    appId: '1:550492156639:ios:c17bcba3bc3191abfaaf6a',
    messagingSenderId: '550492156639',
    projectId: 'my-first-project-fd056',
    storageBucket: 'my-first-project-fd056.appspot.com',
    iosClientId: '550492156639-hhl26d696pmdiqbg0916ftik13a76fa7.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstapp',
  );
}
